name: LLM CSV Insights CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          # Make repo root importable so `from app...` works
          PYTHONPATH: ${{ github.workspace }}
          HF_HUB_DISABLE_TELEMETRY: "1"
        run: |
          pytest -q
